### ISSUE TITLE
Ethernet interface does not show up

### ISSUE THREAD

**Issue by compihu** [redrathnure/armbian-mkspi#1]
Should be a device tree issue as if I replace the dtb created during the build with my "cooked" (decompiled from the dtb in original MKS image, fixed the spi display type and recompiled) one, everything works fine.
[rk3328-roc-cc.dtb.gz](https://github.com/redrathnure/armbian-mkspi/files/10328659/rk3328-roc-cc.dtb.gz)

**Comment by redrathnure** [comment]
Ethernet was configured in [0.1.3_23.02.0-trunk.0073](https://github.com/redrathnure/armbian-mkspi/releases/tag/mkspi%2F0.1.3_23.02.0-trunk.0073) build.
