### ISSUE TITLE
LCD TS-35 does not work after updating (September 21, 2023)

### ISSUE THREAD

**Issue by PrintMan133** [redrathnure/armbian-mkspi#15]
### What happened?

LCD TS-35 does not work after updating
OS: Armbian 23.8.1 bullseye 
Distro: armbian 
### How to reproduce?

LCD TS-35 does not work after updating

### Branch

main (main development branch)

### On which host OS are you observing this problem?

Bullseye

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by redrathnure** [comment]
My TS-35 works fine, tested it yesterday with [0.2.1-23.08.0-trunk](https://github.com/redrathnure/armbian-mkspi/releases/tag/mkspi%2F0.2.1-23.08.0-trunk) release. I would recommend to check your hardware , especially contacts and try new release images. 
And please double check you have frozen kernel packages. If you update kernel to latest from official Armbian repo you will loose screen and couple of other hardware components.

**Comment by NexGen-3D-Printing** [comment]
I have this issue with all of the OS images after Kernal v5, I'm running a generic HDMI "Model-B" display, fires up and works out the box in Kernal v5 but will not work with any of the newer images running Kernal 6 or upwards.

May 15 release, Bullseye Current works, all after this, I get not picture.

**Comment by PimpstaPee** [comment]
Touch screen dont work  mks ts35 v1.0 on [https://github.com/redrathnure/armbian-mkspi/releases/tag/mkspi%2F0.3.0-24.2.0-trunk](url)

**Comment by redrathnure** [comment]
@PimpstaPee which image?

**Comment by PimpstaPee** [comment]
@redrathnure @redrathnure [Armbian-unofficial_24.2.0-trunk_Mkspi_bookworm_edge_6.6.7.img.xz](https://github.com/redrathnure/armbian-mkspi/releases/download/mkspi%2F0.3.0-24.2.0-trunk/Armbian-unofficial_24.2.0-trunk_Mkspi_bookworm_edge_6.6.7.img.xz)
Если Вам будет удобно, можно на английском

**Comment by redrathnure** [comment]
@PimpstaPee moved to https://github.com/redrathnure/armbian-mkspi/issues/20

**Comment by redrathnure** [comment]
LCD TS-35 works fine

**Comment by redrathnure** [comment]
LCD TS-35 works fine
