### ISSUE TITLE
For the default (not minimal) install to include enough to build the OS so extra drivers may be built to get to first internet faster

### ISSUE THREAD

**Issue by ChristineBoersen** [redrathnure/armbian-mkspi#23]
### For the default (not minimal) install to include enough to build the OS so extra drivers may be built to get to first internet faster

Goals
- Have build-essential included in non-minimal install
- Have usb-modeswitch included in non-minimal cli (it is part of desktop already due to xmod*)

#21 Continuation of justification for installing kernel headers + source for non-minimal install

### Funding

- I am offering to write up the initial documentation and changes to traditional patch directories.

**Comment by ChristineBoersen** [comment]
Also, nearly, if not all, of this, is needed to build kiauh which is a common way to install klipper and friends, hence, it is much quicker to get the compiled on your host vs on the mkspi cpu  (fast build machine).

**Comment by redrathnure** [comment]
Done, https://github.com/redrathnure/armbian-mkspi/releases/tag/mkspi%2F0.3.2-24.2.0-trunk
