### ISSUE TITLE
The build was too slow

### ISSUE THREAD

**Issue by HasibTheNeWb** [redrathnure/armbian-mkspi#25]
Can anyone give the already made output\images for Debian? Actually i waited almost 3 hours to complete the build. And i cancelled it. If anyone already made the img file for the Debian please share with me. 😥

### Funding

- [x] [I am willing to cover expenses](https://www.armbian.com/contact/)

**Comment by redrathnure** [comment]
Hi, have you checked a [release page](https://github.com/redrathnure/armbian-mkspi/releases)? E.g. [0.3.4-24.2.0-trunk](https://github.com/redrathnure/armbian-mkspi/releases/tag/mkspi%2F0.3.4-24.2.0-trunk) has images for Bookworm and Bullseye distros.

**Comment by HasibTheNeWb** [comment]
> Bullseye

Oh, sorry id didn't notice. Is it possible to install open media vault in this version?

**Comment by redrathnure** [comment]
Should be no problem. It's usual Debian or Ubuntu, whatever you choose.

**Comment by HasibTheNeWb** [comment]
Bro, can you tell me whats is the login username and password, i just installed, but can't login with ssh- username: mks pass: makerbase

**Comment by HasibTheNeWb** [comment]
NVM.
Thank you, man.

**Comment by HasibTheNeWb** [comment]
Getting this error when trying to install open media vault in Mks pi 

-bash: /usr/bin/sudo: Input/output error
-bash: /usr/bin/sudo: Input/output error

**Comment by redrathnure** [comment]
have no idea what this. Perhaps you should try an Ubuntu image, they are tested better.
