### ISSUE TITLE
[Bug]: The v1.0.0-25.2.0 gives me a blank screen on TS35

### ISSUE THREAD

**Issue by FabioM3** [redrathnure/armbian-mkspi#39]
### What happened?

I tried to update to 1.0.0-25.2.0-trunk - bookwork and jammy, but they give just a blank screen on TS35. (I can acess it via ssh).
The last bullseye works normal.
I have a skipr v1.1.

### How to reproduce?

intall latest version to emmc

**Comment by redrathnure** [comment]
> I tried to update to

what does "update" mean? Was it a fresh new installation or you just update kernel packages?
Any /dev/fb* devices? Do you see any unusual or error dmesg  logs?

>  there's no option to toggle GPIO

Yeah, Armbian reworks armbian-config tool. There are some "surprises" here. It's out of my control, I would recommend to ask the question or report a bug in official Armbian forum.

**Comment by FabioM3** [comment]
Is a fresh installation.

The GPIO thing, I think the GPIOs are all on by default.

**Comment by redrathnure** [comment]
It's strange... I just updated my printer (SKIPR) to Noble current (6.6.65) and tested current and edge images on test stand (MKSPI and SKIPR) - everything works fine. 

In worst case you may stay with pre 1.0.0 image, there are no big functional changes.

**Comment by FabioM3** [comment]
I tested bookworm an Jammy current 🤷‍♂️
But is ok, I will stay with bullseye for a few years.
Thanks for this incredible work!
