### ISSUE TITLE
Hi, theres a little bug in the armbian-config > System > Firmware

### ISSUE THREAD

**Issue by onolox** [redrathnure/armbian-mkspi#6]
Hi!, using apt update and apt upgrade does not break the system, but using the armbian-config > System > Firmware option, which in theory is the same bricks the system.

PS: And another thing, the latest image create a little system partition, most people I think uses the eMMC that MKS bundles, it is 8GB. The partition created is 2.4GB, a repartition does the trick too, it's not a big concern, but I think it's good to be mentioned.
The partition of the build of feb. 5 has a good size.

### On which host OS are you observing this problem? Jammy

Thanks for this amazing work!

**Comment by redrathnure** [comment]
Hi @onolox,

this repo has very minor changes to adapt UBoot and Kernel Device Tree for MKS PI board. It does not affect any Armbian, Kernel, Ubuntu etc code itself. So issues with armbian-config is out of scope for this repository. I also have no idea why image or partition sizes were changed. It came from main Armbian repository.

And please pay attention, UBoot and Kernel Device Tree patches for MKS PI were "prepared" based on Renegade (ROC-RK3328-CC) board (in most ugliest way, as you may imaginate it). MKS PI does **not** have it's own board ID and in generally Armbian and other tools identify it as Renegate (ROC-RK3328-CC) board. Of course MKS PI is **not** the Renegade, and neither firmware nor kernel device tree cannot be applied on it.

This is why I would not recommend to use any default kernel/firmware related packages, updates or config overlays from Armbian. IMO it's OK to update non board specific packages, but please do not try to install default kernel or flash any hardware specific updates.
